### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wangziyi0526** [ecomfe/san-cli#216]
![image](https://user-images.githubusercontent.com/26397622/113276884-cd6b7c80-9312-11eb-9723-cc7729e284e7.png)

**Comment by Lohoyo** [comment]
windows 系统找不到 php 的问题的解决办法参见：https://stackoverflow.com/questions/37962406/php-command-not-found-in-my-shell-for-windows-10-neither-in-git-bash-i-tried-al/62319951#62319951

如果没有梯子而访问不了，以下是我把上面的链接里的内容复制粘贴过来的：
Open My Computer Properties
Click on Advance System Setting
Select Environment Variables
Click on Path & Edit
Click new & Add your PHP.exe path (e.g. C:\xampp\php\php.exe) [As shown in the picture](https://i.stack.imgur.com/GjpeU.png)
then Restart

Detail Support available [here](https://www.php.net/manual/en/faq.installation.php#faq.installation.addtopath)
