### ISSUE TITLE
[Bug] css modules

### ISSUE THREAD

**Issue by lx11573** [ecomfe/san-cli#276]
**Version**
The version of San CLI.
3.0.0
**Describe the bug**
使用 cli 创建的 demo 项目中, 在 .san 文件中使用 css modules, 启动项目后, 报 css-loader#module not set 

san.config.js
```js
chainWebpack: config => {
  config.module.rule('css')
    .test(/\.css$/)
    .oneOf('css-module')
        .resourceQuery(/module/)
        .use('style-loader').loader('style-loader')
            .end()
        .use('css-loader').loader('css-loader')
            .options({
                modules: {
                    localIdentName: '[local]_[hash:base64:5]'
                },
                localsConvention: 'camelCase',
                sourceMap: true
            })
            .end()
        .end()
    .oneOf('css-normal')
        .use('style-loader').loader('style-loader')
            .end()
        .use('css-loader').loader('css-loader')
}
```

**Comment by lx11573** [comment]
但是 `san-loader` 的官方示例，不使用 `san-cli`， 直接使用 `webpack.config.js` 是可以的
**PS**：`san-loader` 的示例需要将 `.san` 的 `loader`, `san-hot-loader`变更为 `san-loader` 才可以正常启动， 不知道是不是我这里的问题

**Comment by Lohoyo** [comment]
你在 `san.config.js` 里加上这个配置看行不行。
```js
module.exports = {
    css: {
        requireModuleExtension: false
    }
};
```

**Comment by lx11573** [comment]
> 你在 `san.config.js` 里加上这个配置看行不行。
> 
> ```js
> module.exports = {
>     css: {
>         requireModuleExtension: false
>     }
> };
> ```

额, 可以了

**Comment by Lohoyo** [comment]
好的。这个配置的说明可以在 [San CLI 官方文档](https://ecomfe.github.io/san-cli/config/)里找到。
