### ISSUE TITLE
[Bug]san init 创建一个项目后，npm start 启动失败

### ISSUE THREAD

**Issue by Sheetaa** [ecomfe/san-cli#294]
**Version**
san-cli 4.0.0
node v16.6.1
npm 7.20.5

**Describe the bug**
![image](https://user-images.githubusercontent.com/4032009/128656561-11f5e03b-b1da-4a72-a296-92618c47b1da.png)

**To Reproduce**
1. san init https://github.com/ksky521/san-project.git san-demo
2. npm i
3. npm start

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Lohoyo** [comment]
试试 `san init san-demo`，即不显示地指定脚手架模板的地址，使用默认的。

**Comment by Sheetaa** [comment]
之前采用默认的 pull 失败了，才手动指定的。现在重新采用默认的没有问题了

**Comment by Lohoyo** [comment]
默认 pull 失败了应该是因为网络有问题（此时自己从 github clone 项目应该也不会成功）。
而手动指定失败的原因是，分支不对，如果手动指定成 https://github.com/ksky521/san-project.git#v4 （加上了分支参数），就是默认的情况了。
官方文档有误，我们近期会更正，感谢反馈。

**Comment by Lohoyo** [comment]
官方文档已更新。
