### ISSUE TITLE
[Bug] `san -h` 命令死循环了

### ISSUE THREAD

**Issue by ruimifa** [ecomfe/san-cli#333]
**Version**
4.2.0

**Describe the bug**
1. 输入 `san -h` 让我去官网；
![image](https://user-images.githubusercontent.com/52688412/151135738-24cbaa16-cb2c-49cf-945b-5a64e45f9942.png)

2. 去了官网
![image](https://user-images.githubusercontent.com/52688412/151135885-b34174d2-af9a-43c2-9940-11f067a0f2be.png)

**Comment by ksky521** [comment]
没毛病啊，https://ecomfe.github.io/san-cli/ 就是文档呀
