### ISSUE TITLE
[Bug]san-loader在Windows下路径解析错误

### ISSUE THREAD

**Issue by FisNew** [ecomfe/san-cli#42]
版本
san-loader  0.1.1

运行环境：
node: 10.13.0
windows10

描述：

webpack配置如下：

`
 

> module: {

        rules: [
            {
                test: /\.san$/,
                loader: 'san-loader'
            },
            {
                test: /\.js$/,
                loader: 'babel-loader'
            },
             ...
        ]
    }
`
然后
webpack-dev-server启动

报错
 `
ERROR in ./src/App.san
Module not found: Error: Can't resolve 'F:san-projectsrcApp.san?lang=html&san=&type=template' in 'F:\san-pro
ject\src'
 @ ./src/App.san 6:8-86 11:41-49
 @ ./src/index.js

ERROR in ./src/App.san
Module not found: Error: Can't resolve 'F:san-projectsrcApp.san?lang=js&san=&type=script' in 'F:\san-project
\src'
 @ ./src/App.san 8:4-77 9:4-72 9:4-72 11:33-39
 @ ./src/index.js

ERROR in ./src/App.san
Module not found: Error: Can't resolve 'F:san-projectsrcApp.san?lang=less&san=&type=style&index=0' in 'F:\sa
n-project\src'
 @ ./src/App.san 3:8-78
 @ ./src/index.js
`
正确解析路径应该是  F:\san-project\src\App.san?lang=less&san=&type=style&index=0
在maxos下无此问题存在

**Comment by Lohoyo** [comment]
是否方便提供一个能够重现你的问题的 GitHub 仓库？你可以把在你本地的能重现问题的代码推送到 GitHub 并提供仓库的链接。

**Comment by FisNew** [comment]
好的，晚上提供。




| |
自强
邮箱：ziqiang1994@163.com
|

签名由 网易邮箱大师 定制

在2020年07月09日 11:24，Huyue 写道：

是否方便提供一个能够重现你的问题的 GitHub 仓库？你可以把在你本地的能重现问题的代码推送到 GitHub 并提供仓库的链接。

**Comment by FisNew** [comment]
[仓库地址](https://github.com/FisNew/san-project.git)

我司是银行，最近在公司推行san来兼容IE8，遇到不少问题，请求技术支持
要一个联系方式。我的邮箱地址fisnew@cmbchina.com

**Comment by ksky521** [comment]
这个和 #41 都是一个问题，是windows下面的路径拼错了，san-cli@0.1.4 使用了san-loader@0.1.2 和 san-hot-loader@0.1.2 解决了，联系方式稍后发到邮箱
