### ISSUE TITLE
[Bug] san-hot-loader 

### ISSUE THREAD

**Issue by FisNew** [ecomfe/san-cli#43]
版本
san-loader  0.1.1

运行环境：
node: 10.13.0
windows10

描述：

webpack配置如下：
`
 

>  module: {

           rules: [

            {
                test: /\.san$/,
                use: [
                    {
                        loader: require.resolve('san-hot-loader')
                    },
                    {
                        loader: path.resolve(__dirname, 'node_modules/san-hot-loader/index.js'),
                        options: {
                            compileTemplate: 'aPack'
                        }
                    }
                ]
            },
            {
                test: /\.js$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            plugins: [
                                require.resolve('@babel/plugin-proposal-class-properties'),
                                require.resolve('san-hot-loader/lib/babel-plugin')
                            ],
                            presets: [
                                [
                                    require.resolve('@babel/preset-env'),
                                    {
                                        targets: {
                                            browsers: '> 1%, last 2 versions'
                                        },
                                        modules: false
                                    }
                                ]
                            ]
                        }
                    }
                ]
            },
            ......
        ]
    },
    plugins: [
        new SanLoaderPlugin()
    ]
`
然后
webpack-dev-server启动

报错

>  

ERROR in ./src/App.san 1:0
Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/san-hot-loader/index.js
 * ./node_modules/san-hot-loader/index.js
You may need an additional loader to handle the result of these loaders.
 @ ./src/index.js 2:0-24 3:14-17

**Comment by ksky521** [comment]
能否创建个repo，提交下完整代码，我们在windows下面看下

**Comment by FisNew** [comment]
好的，晚上。




| |
自强
邮箱：ziqiang1994@163.com
|

签名由 网易邮箱大师 定制

On 07/09/2020 12:18, 三水清 wrote:

能否创建个repo，提交下完整代码，我们在windows下面看下

**Comment by FisNew** [comment]
[仓库地址](https://github.com/FisNew/san-project2.git)

**Comment by Lohoyo** [comment]
你好，我们已定位到原因：你的 webpack 配置有一处写错了，`loader: path.resolve(__dirname, 'node_modules/san-hot-loader/index.js')`，这里应该写 san-loader 而不是 san-hot-loader。

**Comment by FisNew** [comment]
> 你好，我们已定位到原因：你的 webpack 配置有一处写错了，`loader: path.resolve(__dirname, 'node_modules/san-hot-loader/index.js')`，这里应该写 san-loader 而不是 san-hot-loader。

麻烦了。

path.resolve(__dirname, 'node_modules/san-hot-loader/index.js')
请问下这里我是否可以写成loader: require.resolve('san-loader') ?

在我san-hot-loader改为san-hot-loader之后出现了新的问题：
```
ERROR in ./src/App.san 17:93
Module parse failed: Bad character escape sequence (17:93)
File was processed with these loaders:
 * ./node_modules/san-hot-loader/index.js
 * ./node_modules/san-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     if (module.hot) {
|         var __HOT_API__ = require('D:\san-project\node_modules\san-hot-loader\lib\runtime\component-client-api.js');
>         var __HOT_UTILS__ = require('D:\san-project\node_modules\san-hot-loader\lib\runtime\utils.js');
| 
|         var __SAN_COMPONENT__ = __HOT_UTILS__.getExports(module);
 @ ./src/main.js 1:0-24 2:14-17
 @ multi @babel/polyfill ./src/main.js

```

**Comment by FisNew** [comment]
> > 你好，我们已定位到原因：你的 webpack 配置有一处写错了，`loader: path.resolve(__dirname, 'node_modules/san-hot-loader/index.js')`，这里应该写 san-loader 而不是 san-hot-loader。
> 
> 麻烦了。
> 
> path.resolve(__dirname, 'node_modules/san-hot-loader/index.js')
> 请问下这里我是否可以写成loader: require.resolve('san-loader') ?
> 
> 在我san-hot-loader改为san-hot-loader之后出现了新的问题：
> 
> ```
> ERROR in ./src/App.san 17:93
> Module parse failed: Bad character escape sequence (17:93)
> File was processed with these loaders:
>  * ./node_modules/san-hot-loader/index.js
>  * ./node_modules/san-loader/index.js
> You may need an additional loader to handle the result of these loaders.
> |     if (module.hot) {
> |         var __HOT_API__ = require('D:\san-project\node_modules\san-hot-loader\lib\runtime\component-client-api.js');
> >         var __HOT_UTILS__ = require('D:\san-project\node_modules\san-hot-loader\lib\runtime\utils.js');
> | 
> |         var __SAN_COMPONENT__ = __HOT_UTILS__.getExports(module);
>  @ ./src/main.js 1:0-24 2:14-17
>  @ multi @babel/polyfill ./src/main.js
> ```

**Comment by ksky521** [comment]
更新最新版，再试下

**Comment by Lohoyo** [comment]
> 请问下这里我是否可以写成loader: require.resolve('san-loader') ?

可以的。

**Comment by ksky521** [comment]
没问题我关了
