### ISSUE TITLE
[Bug]部署流程中验证邮箱无法通过：缺失保存邮箱验证数据的临时目录

### ISSUE THREAD

**Issue by jiangxinge** [ecomfe/san-cli#61]
**Version**
san-cli@0.1.4
deploy-files@0.0.4

**Describe the bug**
在使用`--remote`远程部署目标开发机时，首先会通过输入的邮箱做身份认证，但会出现如下报错信息，表示读取不到用户目录下的一个文件：
```bash
✔ The output directory is ready to be deployed. Duration 35.904/34.204s, Webpack 4.44.1.                                                                           8:55:19 PM
prompt: Enter your email:  
error:   The specified value must be a valid email address.
prompt: Enter your email:  MY_NAME@xxxx.com

ERROR  ENOENT: no such file or directory, open '/Users/MY_NAME/.deploy-tmp/deploy.json'
......
......
```
经过debug发现，部署过程中，有一个读取`/Users/MY_NAME/.deploy-tmp/`目录文件的方法被调用了（方法的位置`./node_modules/deploy-files/fsr.js`），但是本地却没有这么一个目录
```
function getTmpFile() {
    return require('os').homedir() + '/.deploy-tmp/deploy.json';
}
```

参考@baidu/hulk-cli@2.1.6，@baidu/upload-file@0.1.1，读取的目录是`/Users/MY_NAME/.hulk-templates/`，因为安装完hulk-cli的同时，这个目录就已经存在了，所以能顺利部署

**Expected behavior**
san-cli安装时保留一个临时目录`/Users/MY_NAME/.deploy-tmp/`

**Comment by Lohoyo** [comment]
如果部署之前你手动建立一个名为`/Users/MY_NAME/.deploy-tmp/`的目录，那么能顺利部署吗？

**Comment by jiangxinge** [comment]
> 如果部署之前你手动建立一个名为`/Users/MY_NAME/.deploy-tmp/`的目录，那么能顺利部署吗？

可以。当前项目中的临时解决方案就是，提前创建这样一个目录，即便没有deploy.json这个文件
