### ISSUE TITLE
san-cli创建的demo，无法使用sass或scss[Bug]

### ISSUE THREAD

**Issue by lx11573** [ecomfe/san-cli#85]
**Version**
The version of San CLI.
3.0.0
**Describe the bug**
1、通过`san-cli`创建demo时(使用的ksky521/san-project )，选择的`sass`，但是项目建完后，项目的demo中的预制文件后缀是`.less`
2、创建.san单文件时使用`style`的`lang`是scss/sass时无法通过编译，先是提示需要安装Sass-loader，安装完毕后，编译无法通过。

**Comment by ksky521** [comment]
这是 https://github.com/ksky521/san-project的问题，记录下来了，后面补充下sass的demo

**Comment by jinzhan** [comment]
已修复，重新安装 san-cli 最新版即可。
